import jsPDF from 'jspdf'
import type { FlowInstance, FlowTemplate } from '../types/workflow.types'

export const getPlaceholderForStep = (stepTitle: string): string => {
  const placeholders: Record<string, string> = {
    'Job Title': '{{jobTitle}}',
    'Job Mission': '{{jobMission}}',
    'Job Scope & Reach': '{{jobScope}}',
    'Key Responsibilities': '{{keyResponsibilities}}',
    'Required Qualifications': '{{qualifications}}',
  }
  return placeholders[stepTitle] || `{{${stepTitle.toLowerCase().replace(/\s+/g, '')}}}`
}

export const generateFinalDocument = (instance: FlowInstance, template: FlowTemplate): string => {
  // Generate final document using the template's outputTemplate
  let finalDoc =
    template.outputTemplate ||
    `# {{jobTitle}}

## Position Overview
{{jobMission}}

## Scope & Impact
{{jobScope}}

## Key Responsibilities
{{keyResponsibilities}}

## Qualifications
{{qualifications}}

## About {{organizationName}}
{{organizationDescription}}

---
*Generated by IntelliTrade Salarium on {{generationDate}}*`

  // Replace placeholders with actual content
  const stepResponses = Array.isArray(instance.stepResponses) ? instance.stepResponses : []
  stepResponses.forEach((response, index) => {
    const stepData = template.steps[index]
    if (stepData && response.aiGeneratedContent) {
      const placeholder = getPlaceholderForStep(stepData.title)
      finalDoc = finalDoc.replace(placeholder, response.aiGeneratedContent)
    }
  })

  // Add generation metadata
  finalDoc = finalDoc.replace('{{generationDate}}', new Date().toLocaleDateString())
  finalDoc = finalDoc.replace('{{organizationName}}', 'Your Organization')
  finalDoc = finalDoc.replace(
    '{{organizationDescription}}',
    'A forward-thinking organization committed to excellence.',
  )

  return finalDoc
}

export const downloadAsPDF = async (instance: FlowInstance): Promise<void> => {
  if (!instance?.finalDocument) return

  try {
    const doc = new jsPDF()

    // Add Salarium branding header
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('SALARIUM', 20, 30)

    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('AI-Powered HR Solutions', 20, 40)

    // Add a line separator
    doc.line(20, 45, 190, 45)

    // Add document title
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(instance.title, 20, 60)

    // Process the markdown content for PDF
    const lines = instance.finalDocument.split('\n')
    let yPosition = 80
    const pageHeight = doc.internal.pageSize.height
    const margin = 20
    const lineHeight = 6

    for (const line of lines) {
      // Check if we need a new page
      if (yPosition > pageHeight - 30) {
        doc.addPage()
        yPosition = 30
      }

      if (line.startsWith('# ')) {
        // Main heading
        doc.setFontSize(16)
        doc.setFont('helvetica', 'bold')
        doc.text(line.substring(2), margin, yPosition)
        yPosition += lineHeight + 4
      } else if (line.startsWith('## ')) {
        // Sub heading
        doc.setFontSize(14)
        doc.setFont('helvetica', 'bold')
        doc.text(line.substring(3), margin, yPosition)
        yPosition += lineHeight + 2
      } else if (line.startsWith('### ')) {
        // Sub-sub heading
        doc.setFontSize(12)
        doc.setFont('helvetica', 'bold')
        doc.text(line.substring(4), margin, yPosition)
        yPosition += lineHeight + 1
      } else if (line.startsWith('• ') || line.startsWith('* ')) {
        // Bullet points
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        const bulletText = line.substring(2)
        const splitText = doc.splitTextToSize(bulletText, 160)
        doc.text('• ' + splitText[0], margin + 5, yPosition)
        for (let i = 1; i < splitText.length; i++) {
          yPosition += lineHeight
          if (yPosition > pageHeight - 30) {
            doc.addPage()
            yPosition = 30
          }
          doc.text('  ' + splitText[i], margin + 5, yPosition)
        }
        yPosition += lineHeight
      } else if (line.trim() === '') {
        // Empty line
        yPosition += lineHeight / 2
      } else if (line.startsWith('---')) {
        // Separator line
        doc.line(margin, yPosition, 190, yPosition)
        yPosition += lineHeight
      } else {
        // Regular text
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        const splitText = doc.splitTextToSize(line, 170)
        for (const textLine of splitText) {
          if (yPosition > pageHeight - 30) {
            doc.addPage()
            yPosition = 30
          }
          doc.text(textLine, margin, yPosition)
          yPosition += lineHeight
        }
      }
    }

    // Add footer
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.text(
        `Generated by Salarium AI-Powered HR Solutions - Page ${i} of ${pageCount}`,
        margin,
        pageHeight - 10,
      )
    }

    // Save the PDF
    doc.save(`${instance.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`)
  } catch (error) {
    console.error('PDF download error:', error)
    throw new Error('Failed to download PDF')
  }
}

export const downloadAsTXT = async (instance: FlowInstance): Promise<void> => {
  if (!instance?.finalDocument) return

  try {
    // Add Salarium branding to the document
    const brandedContent = `
╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║                            SALARIUM                                          ║
║                    AI-Powered HR Solutions                                   ║
║                                                                              ║
║    Professional Job Description Generated with AI Assistance                ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

${instance.finalDocument}

────────────────────────────────────────────────────────────────────────────────

Generated by Salarium AI-Powered HR Solutions
Visit us at: https://salarium.com
Contact: info@salarium.com

This document was generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}
`

    const blob = new Blob([brandedContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)

    const link = document.createElement('a')
    link.href = url
    link.download = `${instance.title.replace(/[^a-zA-Z0-9]/g, '_')}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    URL.revokeObjectURL(url)
  } catch (error) {
    console.error('TXT download error:', error)
    throw new Error('Failed to download TXT file')
  }
}

export const downloadAsWord = async (instance: FlowInstance): Promise<void> => {
  if (!instance?.finalDocument) return

  try {
    // Convert markdown to a simple HTML format for Word
    const htmlContent = instance.finalDocument
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^\* (.+)$/gm, '<li>$1</li>')
      .replace(/^• (.+)$/gm, '<li>$1</li>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/\n/g, '<br>')

    const wordContent = `
      <html>
        <head>
          <meta charset="utf-8">
          <title>${instance.title}</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }
            h1 { color: #333; border-bottom: 2px solid #333; }
            h2 { color: #555; margin-top: 30px; }
            h3 { color: #777; }
            li { margin: 5px 0; }
            ul { padding-left: 20px; }
          </style>
        </head>
        <body>
          ${htmlContent}
        </body>
      </html>
    `

    const blob = new Blob([wordContent], {
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    })
    const url = URL.createObjectURL(blob)

    const link = document.createElement('a')
    link.href = url
    link.download = `${instance.title.replace(/[^a-zA-Z0-9]/g, '_')}.doc`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    URL.revokeObjectURL(url)
  } catch (error) {
    console.error('Word download error:', error)
    throw new Error('Failed to download Word document')
  }
}

export const printDocument = (instance: FlowInstance, editableFinalDocument?: string): void => {
  if (!editableFinalDocument && !instance?.finalDocument) return

  const printContent = editableFinalDocument || instance?.finalDocument || ''

  // Create a new window for printing
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  // Convert markdown to HTML for better printing
  const htmlContent = printContent
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^\* (.+)$/gm, '<li>$1</li>')
    .replace(/^• (.+)$/gm, '<li>$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\n/g, '<br>')

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${instance?.title || 'Job Description'}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 40px;
            color: #333;
          }
          h1 {
            color: #333;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          h2 {
            color: #555;
            margin-top: 30px;
            margin-bottom: 15px;
          }
          h3 {
            color: #777;
            margin-top: 20px;
            margin-bottom: 10px;
          }
          li {
            margin: 5px 0;
          }
          ul {
            padding-left: 20px;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 20px;
          }
          .header h1 {
            color: #6366f1;
            border: none;
            margin: 0;
          }
          .header p {
            color: #666;
            margin: 5px 0;
          }
          @media print {
            body { margin: 20px; }
            .header { page-break-inside: avoid; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>SALARIUM</h1>
          <p>AI-Powered HR Solutions</p>
          <p>Professional Job Description</p>
        </div>
        ${htmlContent}
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
          Generated by Salarium AI-Powered HR Solutions on ${new Date().toLocaleDateString()}
        </div>
      </body>
    </html>
  `)

  printWindow.document.close()
  printWindow.focus()

  // Wait for content to load then print
  setTimeout(() => {
    printWindow.print()
    printWindow.close()
  }, 250)
}

export const copyToClipboard = async (content: string): Promise<void> => {
  try {
    await navigator.clipboard.writeText(content)
  } catch (error) {
    console.error('Copy to clipboard failed:', error)
    throw new Error('Failed to copy to clipboard')
  }
}

export const shareOnSocial = (
  platform: 'linkedin' | 'twitter' | 'facebook',
  instance: FlowInstance,
): void => {
  if (!instance?.title) return

  const jobTitle = instance.title.replace('Job Description - ', '')
  const shareText = `Check out this job opportunity: ${jobTitle} - Created with Salarium AI-Powered HR Solutions`
  const shareUrl = window.location.href

  const urls = {
    linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}&title=${encodeURIComponent(shareText)}`,
    twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`,
    facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`,
  }

  window.open(urls[platform], '_blank', 'width=600,height=400')
}
